id: 8d53316f469e43e8ab322f6ff9f59fc8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_186-The_Teaching_on_the_Extraordinary_Transformation-v2
  language: en
  author: ''
  volume: {}
